### ISSUE TITLE
Textures appear faded

### ISSUE THREAD

**Issue by NHodgesVFX** [EXPWorlds/Godot-Cel-Shader#1]
When adding a texture it appears faded. I attempted to play around with the settings which unfortunately didn't help.

Spatial Material:
![SpatialMaterial](https://user-images.githubusercontent.com/11403345/75072767-26d56b00-54c6-11ea-93ca-7d837ca2f881.PNG)

Cel Shader:
![CelShader](https://user-images.githubusercontent.com/11403345/75072769-276e0180-54c6-11ea-9645-7af84f79376d.PNG)

**Comment by DaveDaDev** [comment]
Okay, thanks for the feedback and the nice example images. I'll see if I can reproduce and correct it.

**Comment by DaveDaDev** [comment]
Thanks mate, legit find. I added "ambient_light_disabled" to the render mode, and also for some reason both the base and shade Sampler2Ds need the "hint_albedo" to display correct colors. Not quite sure why...life is a mystery.
